#!/usr/bin/env bash
set -euo pipefail

source "$(dirname "$0")/_common"
cd "$repository_root"
require_mint
run mint run swiftformat --lint .
run mint run swiftlint lint --strict --config .swiftlint.yml
